### ISSUE TITLE
Example bash script to batch convert files.

### ISSUE THREAD

**Issue by StyraxBenzoin** [shipurjan/subtitle-to-lrc#1]
Not an issue, but maybe a useful bash script for people that want to convert a lot of files in a directory. 

```
#!/bin/bash

# Specify the full path to the subtitle-to-lrc executable
SUBTITLE_TO_LRC="/path/to/subtitle-to-lrc"

# Check if the subtitle-to-lrc command is available
if [ ! -x "$SUBTITLE_TO_LRC" ]; then
    echo "subtitle-to-lrc command not found or not executable. Please check the path."
    exit 1
fi

# Create an output directory if it doesn't exist
output_dir="converted_lrc"
mkdir -p "$output_dir"

# Loop through all .srt files in the current directory
for file in *.srt; do
    # Check if there are any .srt files
    if [ ! -e "$file" ]; then
        echo "No .srt files found in the current directory."
        exit 0
    fi

    # Define the output filename by replacing .srt with .lrc and prepending the output directory
    output_file="$output_dir/${file%.srt}.lrc"

    # Convert the subtitle file to .lrc format
    "$SUBTITLE_TO_LRC" "$file" "$output_file"

    # Check if the conversion was successful
    if [ $? -eq 0 ]; then
        echo "Converted: $file -> $output_file"
    else
        echo "Failed to convert: $file"
    fi
done

```

*Instructions to Use the Script:*
- Open a text editor and copy the script above.
- Save the file with a name like `convert_srt_to_lrc.sh`.
- Make the script executable by running the following command in your terminal: `chmod +x convert_srt_to_lrc.sh`
- Navigate to the directory containing your .srt files and copy `convert_srt_to_lrc.sh` there.
- Run the script: `./convert_srt_to_lrc.sh`

This script will convert all `.srt` files in the current directory to `.lrc` format while keeping the same filename (just changing the extension).

Thanks ChatGPT :)

**Comment by shipurjan** [comment]
Thanks!

**Comment by StyraxBenzoin** [comment]
Thanks for making a great tool!
